# Changes here will be overwritten by Copier
_commit: v0.0.1
_src_path: gh:ninanor/python-template
author_name: Francesco Frassinelli
debug: false
default_branch_name: main
docker: false
email: francesco.frassinelli@nina.no
project_name: senorge tools
project_slug: senorge_tools
repo_name: senorge_tools
repo_org: ninanor
template_type: python
type_annotations: false
